import { AnchorProvider, Program, Wallet, BN, type Idl } from "@coral-xyz/anchor";
import { Keypair, PublicKey } from "@solana/web3.js";
import { readFileSync } from "node:fs";
import { connection } from "./rpc.js";
import { pda } from "./pdas.js";

// The IDL is generated by `anchor build` in the program repo and copied to idl/stockland.json.
const idl = JSON.parse(readFileSync(new URL("../../idl/stockland.json", import.meta.url), "utf8")) as Idl;

/** Anchor client bound to a signer (crank/sponsor) or read-only. */
export function programWith(signer?: Keypair) {
  const wallet = signer ? new Wallet(signer) : ({ publicKey: PublicKey.default, signTransaction: async (t: never) => t, signAllTransactions: async (t: never) => t } as unknown as Wallet);
  return new Program(idl, new AnchorProvider(connection, wallet, { commitment: "confirmed" }));
}

// Decoded account shapes we rely on (Anchor returns BN for u64/u128, plain arrays for fixed arrays).
export type GlobalConfig = { admin: PublicKey; crank: PublicKey; usdcMint: PublicKey; currentEpoch: BN; paused: boolean; feeBps: number[] };
export type ProfileAcc = { id: number; count: number; mints: PublicKey[]; weightsBps: number[]; sleeveBps: number };
export type EpochAcc = { id: BN; status: number; count: number; mints: PublicKey[]; buyUsdc: BN[]; spentUsdc: BN[]; filledTokens: BN[]; sellTokens: BN[]; soldTokens: BN[]; sellReceivedUsdc: BN[]; totalDeposits: BN };
export type PositionAcc = { owner: PublicKey; profileId: number; shares: BN[]; sleeveUsdc: BN; tier: number; tenureStart: BN };
export type PendingDepositAcc = { owner: PublicKey; epochId: BN; profileId: number; amount: BN; mode: number; settled: boolean };
export type PendingSellAcc = { owner: PublicKey; epochId: BN; mint: PublicKey; tokens: BN; settled: boolean };
export type AssetVaultAcc = { mint: PublicKey; tokenAccount: PublicKey; totalShares: BN };

type Accounts = { globalConfig: Fetch<GlobalConfig>; profile: Fetch<ProfileAcc>; epoch: Fetch<EpochAcc>; userPosition: Fetch<PositionAcc>; pendingDeposit: Fetch<PendingDepositAcc>; pendingSell: Fetch<PendingSellAcc>; assetVault: Fetch<AssetVaultAcc> };
type Fetch<T> = { fetch: (k: PublicKey) => Promise<T>; fetchNullable: (k: PublicKey) => Promise<T | null>; all: (filters?: unknown[]) => Promise<{ publicKey: PublicKey; account: T }[]> };
export const accounts = (p: Program) => p.account as unknown as Accounts;

export async function fetchConfig() { return accounts(programWith()).globalConfig.fetch(pda.config()); }
export async function fetchEpoch(id: bigint) { return accounts(programWith()).epoch.fetch(pda.epoch(id)); }
export async function fetchProfile(id: number) { return accounts(programWith()).profile.fetch(pda.profile(id)); }
export async function fetchPosition(owner: PublicKey) { return accounts(programWith()).userPosition.fetchNullable(pda.position(owner)); }
export const epochMemcmp = (epochId: bigint) => [{ memcmp: { offset: 8 + 32, bytes: bs58ish(new BN(epochId.toString()).toArrayLike(Buffer, "le", 8)) } }];
function bs58ish(b: Buffer) { // anchor memcmp wants base58
  const ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"; let n = BigInt("0x" + b.toString("hex")); let s = "";
  while (n > 0n) { s = ALPHABET[Number(n % 58n)] + s; n /= 58n; } for (const x of b) { if (x === 0) s = "1" + s; else break; } return s || "1";
}
